name: Delete Review Branch

on:
  pull_request:
    types:
        - closed



jobs:



  DeleteReviewBranch:
    env:
        GH_TOKEN: ${{secrets.CODE_REVIEW}}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Get Branch Reference
        uses: actions/checkout@v2 

      - name: Delete Branch
        run: |
            echo "Deleting Branch"
            git push origin --delete ${{github.head_ref}}
