name: Delete Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Branch
        if: github.event.pull_request.merged == true
        uses: SvanBoxel/delete-merged-branch@1.4.3
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
