# This is a basic workflow to help you get started with Actions

name: CreateReviewPR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  FormatAndCreatePR:
    # permissions for the job
    permissions: write-all
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{github.token}}
      BRANCHTOMERGE: main
      LABELS: automated-ci-review
      REVIEWBRANCH: review-${{github.triggering_actor}}-${{github.sha}}
      REVIEWCOMMITMSG: (CI) Automated Review Branch Commit
      PRTITLE: (CI) - Automated Pull Request For Review ${{github.event.head_commit.author}} ${{github.sha}}
      PRBODY: |
        ${{github.event.head_commit.author}} has pushed a commit to the dev branch, which has triggered
        an automated workflow that created a review branch, and submitted this automated PR for review.
        Message: ${{github.event.head_commit.message}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Create Temporary Branch, Commit To That Branch, Then Open PR To Main
      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
            token: ${{secrets.GITHUB_TOKEN}}
      - run: |
          echo "Checked Out Branch"
      - name: Create New Branch
        run: |
          git checkout -b ${{env.REVIEWBRANCH}}
      - name: Check Success
        if: ${{ !success() }}
        run: |
          echo "(-) Failed To Create Review Branch : ${{env.REVIEWBRANCH}}"
          exit 1
      - name: Commit Source To Review Branch ${{env.REVIEWBRANCH}}
        run: |
          echo "(*) Attempting To Commit To Review Branch : ${{env.REVIEWBRANCH}}"
          git status
          git add .
          git commit -M ${{env.REVIEWCOMMITMSG}}
          git push

      - name: Check Success
        if: ${{ !success() }}
        run: |
          echo "(-) Failed To Commit Source To Review Branch : ${{env.REVIEWBRANCH}}"
          exit 1
          

      - name: Create Pull Request Into Main For Review
        run: |
          echo "(*) Creating Pull Request"
          gh pr create --base ${{env.BRANCHTOMERGE}} --head ${{env.REVIEWBRANCH}} --title ${{env.PRTITLE}} --body ${{env.PRBODY}} --label ${{env.LABELS}}
      
      - name: Check Success
        if: ${{ !success() }}
        run: |
          echo "(-) Failed To Create Pull Request For Review"

          

