# This is a basic workflow to help you get started with Actions

name: Post Push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # permissions for the job
    permissions: write-all
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup Rust Toolchain & Check Code With Rust Fmt
      - name: Install Rust Toolchain (nightly)
        uses: dtolnay/rust-toolchain@nightly

      - name: Install Rust Fmt
        run: rustup component add rustfmt
      
      - uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          mode: commit
      # Create PR On Main
      - name: Create PR
        uses: peter-evans/create-pull-request@v5.0.2
        with:
            token: ${{secrets.GITHUB_TOKEN}}
            commit-message: CI Processing For Auto-PR To Main
            base: main
            branch: valid-revisions
            title: (CI) - ${{github.actor}} - ${{github.sha}} - ${{github.event.head_commit.timestamp}}
            body: |
              This PR Was Generated Because ${{github.actor}}
              Pushed A Commit To The Development Branch Which Seemingly
              Passed All Tests In The Current Workflow ${{github.workflow_ref}}.
              Commit SHA: ${{github.sha}}
              Commit Message: ${{github.event.head_commit.message}} ${{github.event.head_commit.timestamp}}


