name: Security Audit

on:
    pull_request:
        branches: [main]

jobs:
    security-audit:
        permissions: write-all
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{secrets.CODE_REVIEW}}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3